###########################
########## LDAP  ##########
###########################
[ldap]
enabled = false
user = "cn=admin,dc=org,dc=com"
password = "admin"
hostname = "localhost"
port = 389
base_dn = "dc=org,dc=com"
search_attribute = "cn"

###########################
########## SQLite #########
###########################
[sqlite]
enabled = false
path = "./sqlite.db"
user = ""
password = ""

###########################
########## GITHUB #########
###########################
[github]
token = ""
org = ""
suf = ""
ignore = "" # Format -> "item1,item2,item3..."
delete = false

###########################
########## SMTP  ##########
###########################
[smtp]
enabled = true
host = "smtp.gmail.com"
port = 587
user = "user@gmail.com"
password = ""
from_address = "user@gmail.com"
from_name = "User"
to_addresses = "user@gmail.com,user2@gmail.com" # Format -> "item1,item2,item3..."
